name = "spectral1o"
uuid = "2b401c16-ebc6-47e4-b9ce-2892af244d02"
authors = ["André <andrezito300@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
